%% Import data from text file
% Script for importing data from the following text file:
%
filename_L = 'C:\Users\u0117545\KU Leuven\An De Groef - DATA\UL Functioning pilot test\Trail 2\csv\MOS2D31170535 (2022-09-26)RAW L.csv';
filename_R = "C:\Users\u0117545\KU Leuven\An De Groef - DATA\UL Functioning pilot test\Trail 2\csv\MOS2D31170705 (2022-09-26)RAW R.csv";
TR = timerange("23/09/2022 10:50:00.000", '23/09/2022 11:22:00.000');

%
% Auto-generated by MATLAB on 04-Oct-2022 13:54:53

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [12, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Timestamp", "AccelerometerX", "AccelerometerY", "AccelerometerZ"];
opts.VariableTypes = ["datetime", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Timestamp", "InputFormat", "dd/MM/yyyy HH:mm:ss.SSS");

% Import the data
L = readtable(filename_L, opts);
R = readtable(filename_R, opts);
%% Clear temporary variables
clear opts

%% create timetable data
L_time = table2timetable(L);

data.L = L_time(TR,:);
figure
stackedplot(data.L)

R_time = table2timetable(R);
data.R = R_time(TR,:);
figure; 
stackedplot(data.R)

% phase plot x-y
figure; plot(data.R.AccelerometerY,data.R.AccelerometerX, '*')
%% inport test data LUM 
data_lum = readtable("C:\Users\u0117545\Documents\GitHub\MachineLearningActigraph\model\RSE_026_NP.csv");

figure; 
stackedplot(data_lum)

height(data_lum)
height(data.R)
height(data.L)

%% Import axis orientation file 
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [12, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Timestamp", "AccelerometerX", "AccelerometerY", "AccelerometerZ"];
opts.VariableTypes = ["datetime", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Timestamp", "InputFormat", "dd/MM/yyyy HH:mm:ss.SSS");

Axis_R = readtable("C:\Users\u0117545\KU Leuven\An De Groef - DATA\UL Functioning pilot test\AxisTest\csv\Jill_test_R (2022-10-10)RAW.csv");
Axis_R = table2timetable(Axis_R);

Axis_L = readtable("C:\Users\u0117545\KU Leuven\An De Groef - DATA\UL Functioning pilot test\AxisTest\csv\Jill_test_L (2022-10-10)RAW.csv");
Axis_L = table2timetable(Axis_L);

figure;
h=stackedplot(Axis_R, 'LineWidth', 1.5);
ax = findobj(h.NodeChildren, 'Type','Axes');
arrayfun(@(axh)yline(axh,0,'m--','LineWidth',1),ax);
arrayfun(@(axh)yline(axh,1, 'g--', 'LineWidth',1),ax);
arrayfun(@(axh)yline(axh,-1, 'k--', 'LineWidth',1),ax);
title('RIGHT arm')

figure;
h = stackedplot(Axis_L, 'LineWidth', 1.5);
ax = findobj(h.NodeChildren, 'Type','Axes');
arrayfun(@(axh)yline(axh,0,'m--','LineWidth',1),ax);
arrayfun(@(axh)yline(axh,1, 'g--', 'LineWidth',1),ax);
arrayfun(@(axh)yline(axh,-1, 'k--', 'LineWidth',1),ax);
title('LEFT arm')